### PR TITLE
Picks

### LINKED ISSUE #89: 次pickしたいやつを載せていくやつ
https://github.com/misskey-dev/misskey/pull/12416 (CHANGELOGに記載されていない点に注意が必要)

### LINKED ISSUE #94: 絵文字入力時のサジェストがおかしい
### 💡 Summary

例えばonigiri (入力過程で出るときと、一度閉じて後ろの部分だけ弄って再度出したときでも動きが違うので、こっちの挙動は重複の省き忘れとか?)
image
他には
> :goku: がサジェストに出てこない

https://misskey.niri.la/notes/9mjy7494mp
https://misskey.niri.la/notes/9mjy7qh0mx
> ローマ字でも出てこないね、アプデ後から

https://misskey.niri.la/notes/9mjya330nm
> リアクションピッカーには出てくるからバグっぽそう
https://misskey.niri.la/notes/9mjyanc68z

こっちの挙動は多分別…?

### 🥰 Expected Behavior

絵文字ピッカーと同じように候補が出る

### 🤬 Actual Behavior

重複したり、出ない候補があったりする

### 📝 Steps to Reproduce

_No response_

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* Misskey:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### PR DESCRIPTION
**Pull request by anatawa12**
## What

Fixes #89
Fixes #94

misskey-dev#12416 はdone

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests

### CODE REVIEW

**Review by Sayamame-beans — COMMENTED** [review]
> https://github.com/niri-la/misskey.niri.la/pull/95/commits/8a9891ce6e527600be72fbe83698f260c475f87e

これ中身消えて大丈夫なやつ…??

**Comment by anatawa12** [comment]
ふつーに手順ミスってるやつだ。amendする

**Comment by anatawa12** [comment]
自分的にはLGTM

**Review by Sayamame-beans — APPROVED** [review]
could be ok
pickしたいPR/commitの抜けは無さそう

**Review by niwaniwa — APPROVED** [review]
✅確認

**Comment by anatawa12** [comment]
お二人ありがとうございます。

**Pull request merged**
